### PR TITLE
Fixes to build on ubuntu 24

### PR DESCRIPTION
**Pull request by garyservin**

### CODE REVIEW

**Review by kronos30 — APPROVED** [review]
Does BOOST not work in Ubuntu 24.04 anymore? or is the library version we are using.

Mainly curious.

**Comment by garyservin** [comment]
> Does BOOST not work in Ubuntu 24.04 anymore? or is the library version we are using.
> 
> Mainly curious.

It does, but it seems this repo uses some deprecated headers and code, which causes a warning, which causes the build to fail.

**Review by ayrton04 — APPROVED** [review]

File: tools/rosbag/CMakeLists.txt [hunk 1]
```diff
@@ -14,6 +14,12 @@ catkin_python_setup()
 # Support large bags (>2GB) on 32-bit systems
 add_definitions(-D_FILE_OFFSET_BITS=64)
 
+# ignore BOOST deprecated headers
+add_definitions("-DBOOST_ALLOW_DEPRECATED_HEADERS")
+add_definitions("-DBOOST_BIND_GLOBAL_PLACEHOLDERS")
+add_definitions("-DBOOST_TIMER_ENABLE_DEPRECATED")
+
+
 include_directories(include ${catkin_INCLUDE_DIRS} ${Boost_INCLUDE_DIRS}
```
Comment (ayrton04) [inline tools/rosbag/CMakeLists.txt]: I take it we couldn't have just done a `SYSTEM` include of the Boost headers?

Comment (garyservin) [reply tools/rosbag/CMakeLists.txt]: good point, I think this was one of the first packages I fixed, before we ended up with the `SYSTEM` fix. I'll try that

Comment (garyservin) [reply tools/rosbag/CMakeLists.txt]: Apparently treating them as SYSTEM doesn't really fix the issue, unless I'm missing something else
```
[2025-02-07T19:26:56.673Z] In file included from /home/ec2-user/workspace/ci_tailor-distro_ubuntu24/workspace/src/ros1/ros_comm/locusrobotics-ros_comm-e709834/tools/rosbag/src/encrypt.cpp:39:
[2025-02-07T19:26:56.673Z] /usr/include/boost/progress.hpp:23:3: error: #error This header is deprecated and will be removed. (You can define BOOST_TIMER_ENABLE_DEPRECATED to suppress this error.)
[2025-02-07T19:26:56.673Z]    23 | # error This header is deprecated and will be removed. (You can define BOOST_TIMER_ENABLE_DEPRECATED to suppress this error.)
[2025-02-07T19:26:56.673Z]       |   ^~~~~
[2025-02-07T19:26:56.673Z] In file included from /usr/include/boost/progress.hpp:29:
[2025-02-07T19:26:56.673Z] /usr/include/boost/timer.hpp:21:3: error: #error This header is deprecated and will be removed. (You can define BOOST_TIMER_ENABLE_DEPRECATED to suppress this error.)
[2025-02-07T19:26:56.673Z]    21 | # error This header is deprecated and will be removed. (You can define BOOST_TIMER_ENABLE_DEPRECATED to suppress this error.)
[2025-02-07T19:26:56.673Z]       |   ^~~~~
[2025-02-07T19:26:56.673Z] gmake[4]: *** [CMakeFiles/encrypt.dir/build.make:76: CMakeFiles/encrypt.dir/src/encrypt.cpp.o] Error 1
[2025-02-07T19:26:56.673Z] gmake[3]: *** [CMakeFiles/Makefile2:1027: CMakeFiles/encrypt.dir/all] Error 2
[2025-02-07T19:26:56.673Z] gmake[3]: *** Waiting for unfinished jobs....
[2025-02-07T19:26:56.673Z] gmake[2]: *** [Makefile:146: all] Error 2
```
